### ISSUE TITLE
Video link

### ISSUE THREAD

**Issue by brishnafarahi** [carlomatik/ProgrammierBar#2]
Dear @carlomatik and @muellale ,
could you provide us with a link of a video or the video itself that has to be used as a video on the website?
Regards
Brishna

**Comment by carlomatik** [comment]
Hello, due to it being Silvester I did not reply earlyer.
Since our Bar is closed we can currently not provide any usefull Video of it.
Please use any stock video you can find, or the provided placeholder, which was taken at the bar.
