### ISSUE TITLE
Media Files and Confirmations

### ISSUE THREAD

**Issue by KingsleyOdiboh** [carlomatik/ProgrammierBar#3]
@carlomatik @muellale Could you kindly check through the SVG files we've uploaded, if it matches what you want for your logo? Also please check the uploaded site_template if it matches what you want. At the moment, the entire body is completely black. As per your requests, we intend maintaining the black and white scheme throughout the site as well as include the beer color accent during content implementation. We'd appreciate your feedback as soon as possible.

The template folder is in ProgrammierBar/start/resources/

Many thanks.

**Comment by carlomatik** [comment]
Hello,

it is New Year’s Eve, so we will asap, but not today.

**Comment by brishnafarahi** [comment]
@carlomatik @muellale another template is also in start folder index.html maybe you can have a look at that as well

**Comment by carlomatik** [comment]
Hello,

the SVG Version 1 is what comes closest to what we had in mind, but there is a Keyboard missing.
There colors of all sites do not comply to the vision we had, please read that part again. We had orange (beer like) in mind for the accents.

**Comment by KingsleyOdiboh** [comment]
In that case, we'd appreciate if you send us your logo to work with. Any picture format file would be fine for us. Since we had no sample to work with, we tried making something close to what we considered "minimalistic" as well as graphically appealing.

Regarding Accents, the beer-like accent will only be used for emphasis during content implementation and has not been included into the proposed theme except on hover at the links in footer. A little of that orange could also be seen in the logo. Nevertheless, this might change when we recieve your logo.

**Comment by carlomatik** [comment]
The description of the logo is literally a glass of beer next to a laptop, since any laptop has a keyboard I do not understand the confusion on your part. If sample pictures of beer and laptops are required I can send these.

In it's current state the website does not look graphically appealing, considering the header/footer and the currently used color which was explicitly *NOT* desired to be in the final product.
