### ISSUE TITLE
Website Design Feedback and Docs Folder

### ISSUE THREAD

**Issue by carlomatik** [carlomatik/ProgrammierBar#5]
Hello @farbrish @KingsleyOdiboh ,

while looking through your newly pushed websites I notices that the ones inside the resources folder look better than the ones inside the start folder.
Please add the bars logo to the header as well tho. The logo version 1 looks very good, please add a little white space on the bottom as a trackpad tho.
Please use the webpages inside the resources folder as an inspiration to redo the pages in the start folder, since they do not comply with our wishes.

As stated by the Assignement 2b Moodle page you are supposed to use a docs folder as a source to build a GitHub Pages functionality. Please create such a folder **(urgent)**.

Kind regards

**Comment by brishnafarahi** [comment]
Hallo @carlomatik  @muellale ,
 the ones that are inside the resources folder are the ones that are to be considered, the webpages inside the start folder was the first test work or the prototype that we will delete at the end ( when submitting the assignment ) .
we will consider your wish of adding the logo to the header.
about using the docs folder : as you are the owner only you have the right to assign the docs folder as a source for building the Github Pages not the contributors. 
we are the owners of other repo and we have already changed the settings for them. that's what you have to do as well
regards

**Comment by carlomatik** [comment]
Hello,

@brishnafarahi I am aware of that but as of the time I opened the issue you did not have a docs folder in the repo, I have now added it to the GitHub Pages functionality.
